config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
   get "/publicatons", to: "publications#index", as: "user_root"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :publication
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    #@comment = Comment.new(comment_params)
    @publication = Publication.find(params[:publication_id])
    @comment = @publication.comments.build(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to publication_url(@publication), notice: "Comentario fue creado." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to publication_url(@comment.publication), notice: "Comentario fue actualizado." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to publication_url(@comment.publication), notice: "Comentario eliminado exitosamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :publication_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Contenido:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Publicación:</strong>
    <%= comment.publication_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, "Contenido ", class: "label-dark", style: "display: block" %>
    <%= form.text_area :content %> <br>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.hidden_field :publication_id, value: current_user.id %>
  </div>

  <div>
    <%= form.submit "Actualizar Publicación", class: "btn btn-warning" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editando el Comentario</h1>

<%= render "form", comment: @comment %>

<br>

<!--
<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>
-->

<div>
  <%= link_to "Mostrar esta publicación", @comment.publication, class:"btn btn-dark" %> |
  <%= link_to "Volver a las publicaciones", publications_path, class:"btn btn-dark" %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Mostrar este comentario", comment %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo comentario", new_comment_path %>

app/views/comments/new.html.erb
<h1>Nuevo comentario</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Editar este comentario", edit_comment_path(@comment) %> |
  <%= link_to "Volver a los comentarios", comments_path %>

  <%= button_to "Eliminar este comentario", @comment, method: :delete %>
</div>