config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
   get "/publicatons", to: "publications#index", as: "user_root"
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many_attached :images
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]

  before_action only: [ :create, :edit, :update, :destroy, :new] do
    authorize_request(["admin"])
  end

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    @comment = Comment.new
    @comments = @publication.comments
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id
    @comment = Comment.new
    @comment.user = current_user

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "La publicación fue creada con éxito." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "La publicación fue actualizada." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "La publicación fue destruida" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :description, :user_id, images: [])
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibido guardar esta publicación:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, "Título", class: "label-dark", style: "display: block" %>
    <%= form.text_field :title %> <br>
  </div>

  <div>
    <%= form.label :description, "Descripción", class: "label-dark", style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.file_field :images, multiple: true, style: "width: 200px; height: 200px;" %>
  </div>

  <div>
    <%= form.submit "Actualizar Publicación", class: "btn btn-warning" %> <br> <br>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <div class="texto1">
    <p class="bold-text">
      <%= publication.title %>
    </p>

    <p>
      <%= publication.description %>
    </p>

    <p class="bold-text">
      <%= publication.user.name %>
    </p>

    <% publication.images.each do |img| %>
      <%= image_tag img, style: "width: 400px; height: 400px;" %>
    <% end %>
  </div>

</div>

app/views/publications/edit.html.erb
<h1>Editando la publicación</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Mostrar esta publicación", @publication, class:"btn btn-dark" %> |
  <%= link_to "Volver a las publicaciones", publications_path, class:"btn btn-dark" %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="texto1"> Mis trabajos recientes </h1> <br><br>

<div id="publications">
  <% @publications.each do |publication| %>
    <%= render publication %> <br>
    <p>
      <%= link_to "Mostrar esta publicación", publication, class: "btn btn-dark" %>
    </p>
  <% end %>
</div>

<%= link_to "Nueva Publicación", new_publication_path, class: "btn btn-warning"%>

app/views/publications/new.html.erb
<h1>Nueva publicación</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Volver a las publicaciones", publications_path %>
</div>

app/views/publications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publication %>

<div>

  <% if user_signed_in? %>

    <% if current_user.id == @publication.user_id %> <br> <br>
      <%= link_to "Editar esta pubicación", edit_publication_path(@publication) , class:"btn btn-primary" %> <br> <br>
      <%= button_to "Eliminar esta publicación", @publication, method: :delete , class:"btn btn-danger" %>
    <% end %>

  <% end %> <br>

  <%= link_to "Volver a las publicaciones", publications_path, class:"btn btn-dark" %> <br> <br>
</div>

<div class="comments-section">
  <h2> Reflexiones </h2> <br>

  <% if @comments.any? %>
  <div class="card-deck">
    <% @comments.each do |comment| %>
      <div class="card">
        <div class="card-body d-flex">
          <div class="ml-4 mr-4">
            <%= image_tag current_user.profile, class: "mypfp rounded-circle mr-3 my-auto mb-5", style: "max-width: 100px; max-height: 100px;" %>
          </div>
          <div class="ml-5 mr-5">
            <h5 class="card-title"><strong>Usuario:</strong> <%= comment.user.name %></h5>
            <p class="card-text"><strong>Comentario:</strong> <%= comment.content %></p>
            
            <% if user_signed_in? && current_user.id == comment.user_id %>
              <%= link_to "Editar comentario", edit_comment_path(comment), class: "btn btn-primary" %> <br> <br>
              <%= button_to "Eliminar comentario", comment, method: :delete, class: "btn btn-danger ml-2" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No hay comentarios para esta publicación.</p>
<% end %>

<br>
  <h2>Añadir un comentario</h2>

  <%= form_with(model: @comment, url: publication_comments_path(@publication)) do |form| %>
  <div class="form-group">
    <%= form.label :content, "MeowMentarios " %>
    <%= form.text_area :content, class: "form-control" %> <br>
  </div>
  <%= form.submit "Enviar comentario", class: "btn btn-warning" %> <br> <br>
  <% end %>
</div>
</div>