config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
   get "/publicatons", to: "publications#index", as: "user_root"
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<div id="wrapper">


    <!-- Main -->
        <div id="main">
            <article class="thumb">
                <%= link_to publication_path(1) do %>
                    <%= image_tag '01.jpg' %>
                <% end %>
                <h2>El sol hace su magia</h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(2) do %>
                    <%= image_tag '02.jpg' %>
                <% end %>
                <h2> ¿Árboles, porqué son tan hermosos?</h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(3) do %>
                <%= image_tag '03.jpg' %>
                <% end %>
                <h2>Eres lo más relajante del mundo</h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(4) do %>
                    <%= image_tag '04.jpg' %>
                <% end %>
                <h2>Una pequeña brisa</h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(5) do %>
                <%= image_tag '05.jpg' %>
                <% end %>
                <h2>Combinación de colores perfecta</h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(6) do %>
                <%= image_tag '06.jpg' %>
                <% end %>
                <h2> Mírame</h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(7) do %>
                <%= image_tag '07.jpg' %>
                <% end %>
                <h2>Alegría por sobre todo</h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(8) do %>
                <%= image_tag '08.jpg' %>
                <% end %>
                <h2>Perfección gatuna</h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(9) do %>
                <%= image_tag '09.jpg' %>
                <% end %>
                <h2>Con un maestro</h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(10) do %>
                <%= image_tag '10.jpg' %>
                <% end %>
                <h2>Frágil pero poderoso</h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(11) do %>
                <%= image_tag '11.jpg' %>
                <% end %>
                <h2>Azules </h2>
            </article>
            <article class="thumb">
                <%= link_to publication_path(12) do %>
                <%= image_tag '12.jpg' %>
                <% end %>
                <h2>Entrega</h2>
            </article>
        </div>