config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
   get "/publicatons", to: "publications#index", as: "user_root"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KariPic3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  </head>

  <body class="is-preload">

  		<!-- Wrapper -->
			<div id="wrapper">

          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand ms-5" href="#">
                <%= image_tag '1.png', style: "width: 100px; height: 100px;" %>
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                  <li class="nav-item border border-secondary">
                    <%= link_to "INICIO", homes_index_path, class: "nav-link text-white" %>
                  </li>
                  <% if user_signed_in? %>
                    <li class="nav-item border border-secondary">
                      <%= link_to current_user.email, edit_user_registration_path, class: "nav-link text-white" %>
                    </li>
                    <li class="nav-item border border-secondary">
                      <%= image_tag current_user.profile, class: "nav-link", style: "max-width: 100px; max-height: 100px;" %>
                    </li>
                    <li class="nav-item border border-secondary">
                      <%= link_to "PUBLICACIONES", publications_path, class: "nav-link text-white" %>
                    </li>
                    <li class="nav-item border border-secondary">
                      <%= link_to "SALIR", destroy_user_session_path, method: :delete, class: "nav-link text-white" %>
                    </li>
                  <% else %>
                    <li class="nav-item border border-secondary">
                      <%= link_to "INICIAR SESIÓN", new_user_session_path, class: "nav-link text-white" %>
                    </li>
                    <li class="nav-item border border-secondary">
                      <%= link_to "REGISTRARME", new_user_registration_path, class: "nav-link text-white" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </nav>

    <!-- Header -->
    <header id="header">
      <h1><strong>MULTIVERSO </strong> POR KARIPIC</h1>
      <nav>
          <ul>
              <li><a href="#footer" class="icon solid fa-info-circle">Acerca de mi</a></li>
          </ul>
      </nav>
  </header>


    <div class="container">
     <!-- <p class="notice"><%= notice %></p> -->
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>

	<!-- Footer -->
  <footer id="footer" class="panel">
    <div class="inner split">
      <div>
        <section class="footer">
          <h2 class="white-text">¡Bienvenidos a mi mundo fotográfico!</h2>
          <p class="white-text"> Hola, soy Karina, una apasionada fotógrafa que encuentra la belleza en cada rincón de la vida. Mi objetivo es capturar momentos especiales y transformarlos en recuerdos inolvidables a través de mi lente.</p>
        </section>
        <section class="footer">
          <h2 class="white-text"> Mis redes sociales.</h2>
          <ul class="icons">
            <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
            <li><a href="#" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
            <li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
            <li><a href="#" class="icon brands fa-linkedin-in"><span class="label">LinkedIn</span></a></li>
          </ul>
        </section>
        <p class="copyright white-text">
          &copy; Multiverso: Por KariPic
        </p>
      </div>
      <div>
        <section>
          <a href="#" class="image fit"><%= image_tag '13footer.jpg', style: "max-width: 600px; max-height: 600px;" %></a>
        </section>
      </div>
    </div>
  </footer>

    		<!-- Scripts -->

      <%= javascript_include_tag 'jquery.min.js' %>
      <%= javascript_include_tag 'jquery.poptrox.min.js' %>
      <%= javascript_include_tag 'browser.min.js' %>
      <%= javascript_include_tag 'breakpoints.min.js' %>
      <%= javascript_include_tag 'util.js' %>
      <%= javascript_include_tag 'main.js' %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"> </script>
  </body>
</html>